#!/bin/bash
function send_log(){
CHATID=$(grep -E "^#bot# " "/etc/bot/.bot.db" | cut -d ' ' -f 3)
KEY=$(grep -E "^#bot# " "/etc/bot/.bot.db" | cut -d ' ' -f 2)
URL="https://api.telegram.org/bot$KEY/sendMessage"
TEXT="
<code>────────────────────</code>
<b>⚠️ NOTIF MULTI LOGIN SSH ⚠️</b>
<code>────────────────────</code>
<code>Username   l: </code><code>$user</code>
<code>Limit Ip  : </code><code>$iplimit</code>
<code>Ip.login  : </code><code>$cekcek</code>
<code>Akun Lock : </code><code>15 Minutes</code>
<code>────────────────────</code>
" 
curl -s --max-time 10 -d "chat_id=$CHATID&disable_web_page_preview=1&text=$TEXT&parse_mode=html" $URL >/dev/null
}
mulog=$(fvssh)
data=( `ls /etc/kyt/limit/ssh/ip`);
for user in "${data[@]}"
do
iplimit=$(cat /etc/xray/limit/ssh/ip/$user)
cekcek=$(echo -e "$mulog" | grep $user | wc -l);
if [[ $cekcek -gt $iplimit ]]; then
egrep "^$user" /etc/passwd >/dev/null
passwd -l $user
systemctl restart ws
send_log
echo "passwd -u $user" | at now + 15 minutes > /dev/null
systemctl restart ws
else
echo > /dev/null
fi
sleep 0.1
done
￼
